@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml

LAYOUT_WITH_LEGEND()

Person(client, "Client", "A customer of the site, who wants to request a service.")
Person(entrepreneur, "Entrepreneur", "An entrepreneur, who wants to add a new service or respond to customer requests.")
System(ibs, "Working Service System", "Allows customers to view available services and communicate with the entrepreneur.")

Rel(client, ibs, "Uses")
Rel(entrepreneur, ibs, "Uses")

@enduml
